name: "Documentation Report"
description: Suggest improvements for the docs
title: '[Docs]: '
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what have to be updated.
      placeholder: When I go to the commands.md doc, I notice that it doesn't have a table of contents
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: guidelines
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/aidenybai/million/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: |
        ### Call to Action

        To Commit on this project you should use `npm run commit`. Do not use `git commit` to avoid unwanted issues.