#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

source "$(dirname "$0")/../scripts/helpers.sh"

pending "Checking for errors..."

if [ -n "$(git status src --porcelain)" ]; then
  npx --no-install lint-staged --quiet || exit 1
fi

success "No errors found. Attempting to commit your changes!"